name: CI - JavaScript

on:
  push:

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Format and lint
        run: bun format-lint

      - name: Svelte check
        run: bun check
